{% set name = "elgato" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #git_rev:
  #git_url: https://github.com/appliedbinf/el_gato.git

requirements:
  build:
    - python
    - setuptools
    - skip: True  # [win]

  host: 
    - python >=3.8
    - pip
 
  run:
    - bwa-mem2==2.2.1
    - sambamba==0.8.2
    - freebayes
    - samtools==1.15.1
    - blast==2.13.0
    - ispcr==33.0
    - spades==3.15
    - stringmlst==0.6.3

build:
  noarch: python

test:
  imports:
    - "shlex"
  commands:
    - el_gato.py -h
    - isPcr | head

about:
  home: https://github.com/appliedbinf/el_gato
  license: MIT
